# Form implementation generated from reading ui file 'c:\Users\ROG\Desktop\FIX\GUI\MENU UTAMA.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1164, 899)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 1191, 841))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("c:\\Users\\ROG\\Desktop\\FIX\\GUI\\background.jpg"))
        self.label.setScaledContents(True)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.logout = QtWidgets.QPushButton(Dialog)
        self.logout.setGeometry(QtCore.QRect(80, 440, 421, 101))
        self.logout.setObjectName("logout")
        self.create = QtWidgets.QPushButton(Dialog)
        self.create.setGeometry(QtCore.QRect(80, 300, 421, 101))
        self.create.setObjectName("create")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(40, 30, 491, 241))
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setTitle("")
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.klasifikasi = QtWidgets.QPushButton(self.groupBox)
        self.klasifikasi.setGeometry(QtCore.QRect(40, 30, 421, 81))
        self.klasifikasi.setObjectName("klasifikasi")
        self.data_latih = QtWidgets.QPushButton(self.groupBox)
        self.data_latih.setGeometry(QtCore.QRect(40, 130, 421, 81))
        self.data_latih.setObjectName("data_latih")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(200, 360, 491, 361))
        self.groupBox_2.setAutoFillBackground(False)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_4.setGeometry(QtCore.QRect(40, 30, 421, 81))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_5.setGeometry(QtCore.QRect(40, 130, 421, 81))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_6.setGeometry(QtCore.QRect(40, 230, 421, 101))
        self.pushButton_6.setObjectName("pushButton_6")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.logout.setText(_translate("Dialog", "LOG OUT"))
        self.create.setText(_translate("Dialog", "BUAT AKUN"))
        self.klasifikasi.setText(_translate("Dialog", "KLASIFIKASI"))
        self.data_latih.setText(_translate("Dialog", "DATA LATIH"))
        self.pushButton_4.setText(_translate("Dialog", "KLASIFIKASI"))
        self.pushButton_5.setText(_translate("Dialog", "PushButton"))
        self.pushButton_6.setText(_translate("Dialog", "PushButton"))
