# Form implementation generated from reading ui file 'c:\Users\ROG\Desktop\FIX\GUI\welcomescreen.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1200, 801)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Indonesian, QtCore.QLocale.Country.Indonesia))
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 1221, 811))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("c:\\Users\\ROG\\Desktop\\FIX\\GUI\\background.jpg"))
        self.label.setObjectName("label")
        self.User = QtWidgets.QPushButton(Dialog)
        self.User.setGeometry(QtCore.QRect(490, 550, 341, 51))
        self.User.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(170, 255, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.User.setText("USER")
        self.User.setFlat(True)
        self.User.setObjectName("User")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(440, 140, 451, 81))
        self.label_2.setStyleSheet("font: 36pt \"MS Shell Dlg 2\"; color:rgb(255, 255, 255)")
        self.label_2.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_2.setObjectName("label_2")
        self.login = QtWidgets.QPushButton(Dialog)
        self.login.setGeometry(QtCore.QRect(490, 450, 341, 51))
        self.login.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(170, 255, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.login.setObjectName("login")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(110, 230, 1051, 81))
        self.label_3.setStyleSheet("font: 36pt \"MS Shell Dlg 2\"; color:rgb(255, 255, 255)")
        self.label_3.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(360, 450, 101, 41))
        self.label_4.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";color:rgb(255, 255, 255)")
        self.label_4.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label_4.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Selamat Datang"))
        self.login.setText(_translate("Dialog", "ADMIN"))
        self.label_3.setText(_translate("Dialog", "Aplikasi Penentuan Kematangan Keluak"))
        self.label_4.setText(_translate("Dialog", "Masuk "))
